### ISSUE TITLE
flutter widget test is unstable

### ISSUE THREAD

**Issue by sensuikan1973** [sensuikan1973/pedax#1404]
```
✅ D:\a\pedax\pedax\test\launch_app_with_empty_file_path_test.dart: update book file path as it is
[+8277 ms] test 3: Test harness is no longer needed by test process
[        ] test 3: finished
[        ] Starting coverage collection
[        ] collecting coverage data from Flutter Tester (pid: 3956, running) for test 3 at http://127.0.0.1:57562/eiN-0e5j9BE=/...
[        ] test 3: Test process is no longer needed by test harness
[  +75 ms] Collected coverage data.
[        ] Merging coverage data...
[   +1 ms] Done merging coverage data into global coverage map.
[        ] test 3: cleaning up...
[        ] test 3: ensuring test device is terminated.
[        ] test 3: Terminating flutter_tester process
[        ] test 3: Shutting down test harness socket server
[  +37 ms] test 3: flutter_tester process at pid 3956 exited with code=-1
[        ] test 3: deleting temporary directory
[   +5 ms] test 3: finished

🎉 8 tests passed.
[   +8 ms] Deleting C:\Users\RUNNER~1\AppData\Local\Temp\flutter_tools.95c3c9f1\flutter_test_compiler.fbaa3d77...
[   +5 ms] killing pid 1400
[  +45 ms] Deleting C:\Users\RUNNER~1\AppData\Local\Temp\flutter_tools.95c3c9f1\flutter_test_fonts.5a998155...
[   +2 ms] test package returned with exit code 1
[  +16 ms] coverage information collection complete
[   +1 ms] wrote coverage data to ./coverage/lcov.widget_test.info (size=15832)
[        ] Runtime for phase TestRunner: Wall-clock: 0:01:04.185266; combined: 0:01:04.185346.
[        ] Runtime for phase Compile: Wall-clock: 0:00:17.706458; combined: 0:00:17.706575.
[        ] Runtime for phase Run: Wall-clock: 0:00:45.619080; combined: 0:00:45.619092.
[        ] Runtime for phase CoverageTotal: Wall-clock: 0:00:09.490488; combined: 0:00:00.347565.
[        ] Runtime for phase CoverageCollect: Wall-clock: 0:00:00.442887; combined: 0:00:00.442894.
[        ] Runtime for phase CoverageParseJson: Wall-clock: 0:00:09.122006; combined: 0:00:00.056840.
[        ] Runtime for phase CoverageAddHitmap: Wall-clock: 0:00:00.001157; combined: 0:00:00.001161.
[        ] Runtime for phase CoverageDataCollect: Wall-clock: 0:00:00.018214; combined: 0:00:00.018216.
[        ] Runtime for phase WatcherFinishedTest: Wall-clock: 0:00:09.491920; combined: 0:00:00.348720.
[   +9 ms] "flutter test" took 65,581ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:490:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
[   +2 ms] ensureAnalyticsSent: 0ms
[        ] Running 1 shutdown hook
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by sensuikan1973** [comment]
maybe fixed ...?

**Comment by sensuikan1973** [comment]
hunm...

**Comment by sensuikan1973** [comment]
does https://github.com/sensuikan1973/pedax/pull/1449 resolve ....?

**Comment by sensuikan1973** [comment]
https://github.com/sensuikan1973/pedax/pull/1476/files#diff-09bf57abb6606e76962eea1c483e4caca2da18578d0ad1305e4a97185ec203a9R28-R29 may resolve this ...?

**Comment by sensuikan1973** [comment]
https://github.com/sensuikan1973/pedax/pull/1475/commits/95765f2256a9fc9e86afdaea78ae6ba11ec0d4ff may resolve this ...?

**Comment by sensuikan1973** [comment]
hum...
https://github.com/sensuikan1973/pedax/actions/runs/4975550392/jobs/8902831106?pr=1477

**Comment by sensuikan1973** [comment]
possible related issues

https://github.com/flutter/flutter/issues/124145

**Comment by sensuikan1973** [comment]
https://github.com/flutter/flutter/issues/142810#issuecomment-1952931753
